### ISSUE TITLE
ubyte format requires 0 <= number <= 255

### ISSUE THREAD

**Issue by deepgajjar5** [smartbgp/yabgp#70] opened 2018-03-01 00:46 UTC
Hi, 

I have been encountering this error on Yabgp version 0.4.0 when trying to advertise a SR-TE update with 8 segment-lists. This are the logs from Yabgp:

2018-02-28 16:43:44,013.013 1349 INFO yabgp.api.utils [-] API POST data {u'attr': {u'1': 0, u'8': [u'NO_ADVERTISE'], u'2': [[2, [10, 2, 3]]], u'14': {u'afi_safi': [1, 73], u'nexthop': u'172.24.64.97', u'nlri': {u'color': 20, u'endpoint': u'20.0.255.1', u'distinguisher': 6256}}, u'23': {u'128': [{u'9': 20, u'1': [{u'1': {u'label': 900020}}, {u'1': {u'label': 900003}}, {u'1': {u'label': 900002}}]}, {u'9': 10, u'1': [{u'1': {u'label': 900021}}, {u'1': {u'label': 900004}}, {u'1': {u'label': 900002}}]}, {u'9': 10, u'1': [{u'1': {u'label': 900022}}, {u'1': {u'label': 900003}}, {u'1': {u'label': 900002}}]}, {u'9': 10, u'1': [{u'1': {u'label': 900023}}, {u'1': {u'label': 900004}}, {u'1': {u'label': 900002}}]}, {u'9': 10, u'1': [{u'1': {u'label': 900024}}, {u'1': {u'label': 900003}}, {u'1': {u'label': 900002}}]}, {u'9': 10, u'1': [{u'1': {u'label': 900025}}, {u'1': {u'label': 900004}}, {u'1': {u'label': 900002}}]}, {u'9': 10, u'1': [{u'1': {u'label': 900026}}, {u'1': {u'label': 900004}}, {u'1': {u'label': 900002}}]}, {u'9': 10, u'1': [{u'1': {u'label': 900027}}, {u'1': {u'label': 900003}}, {u'1': {u'label': 900002}}]}], u'0': u'new', u'13': 965796, u'12': 4200}}}
**2018-02-28 16:43:44,013.013 1349 ERROR yabgp.core.protocol [-] ubyte format requires 0 <= number <= 255**

**Comment by xiaopeng163** [comment] 2018-03-01 16:29
Hey,  could you please run yabgp with debug mode (use --verbose in command line), and send this update again?

then paste the log output message here? Thanks

**Comment by deepgajjar5** [comment] 2018-03-07 00:43
Here are the logs after running yabgp with verbose command:

2018-03-06 16:44:09,707.707 13569 INFO yabgp.api.utils decorated_function 37 [-] API POST data {u'attr': {u'1': 0, u'8': [u'NO_ADVERTISE'], u'2': [[2, [30, 2, 3]]], u'14': {u'afi_safi': [1, 73], u'nexthop': u'172.24.64.99', u'nlri': {u'color': 501, u'endpoint': u'30.255.0.1', u'distinguisher': 4294966256}}, u'23': {u'128': [{u'9': 100, u'1': [{u'1': {u'label': 999990}}, {u'1': {u'label': 900005}}, {u'1': {u'label': 900007}}]}, {u'9': 100, u'1': [{u'1': {u'label': 999991}}, {u'1': {u'label': 900006}}, {u'1': {u'label': 900007}}]}, {u'9': 100, u'1': [{u'1': {u'label': 999992}}, {u'1': {u'label': 900005}}, {u'1': {u'label': 900007}}]}, {u'9': 100, u'1': [{u'1': {u'label': 999993}}, {u'1': {u'label': 900006}}, {u'1': {u'label': 900007}}]}, {u'9': 100, u'1': [{u'1': {u'label': 999994}}, {u'1': {u'label': 900005}}, {u'1': {u'label': 900007}}]}, {u'9': 100, u'1': [{u'1': {u'label': 999995}}, {u'1': {u'label': 900005}}, {u'1': {u'label': 900007}}]}, {u'9': 100, u'1': [{u'1': {u'label': 999996}}, {u'1': {u'label': 900006}}, {u'1': {u'label': 900007}}]}, {u'9': 100, u'1': [{u'1': {u'label': 999997}}, {u'1': {u'label': 900006}}, {u'1': {u'label': 900007}}]}], u'0': u'new', u'13': 975796, u'12': 4100}}}
2018-03-06 16:44:09,707.707 13569 DEBUG yabgp.api.utils decorated_function 38 [-] API request environ {'HTTP_AUTHORIZATION': 'Basic YWRtaW46YWRtaW4=', 'HTTP_ACCEPT': 'text/plain', 'CONTENT_TYPE': 'application/json', 'werkzeug.request': <Request 'http://172.24.64.99:8801/v1/peer/172.24.76.173/send/update' [POST]>, 'wsgi.multithread': True, 'SCRIPT_NAME': '', 'wsgi.input': <twisted.web.wsgi._InputStream object at 0x7f61265d9a50>, 'REQUEST_METHOD': 'POST', 'HTTP_HOST': '172.24.64.99:8801', 'PATH_INFO': '/v1/peer/172.24.76.173/send/update', 'SERVER_PROTOCOL': 'HTTP/1.1', 'QUERY_STRING': '', 'wsgi.version': (1, 0), 'HTTP_CONTENT_TYPE': 'application/json', 'HTTP_CONTENT_LENGTH': '1031', 'CONTENT_LENGTH': '1031', 'HTTP_USER_AGENT': 'python-requests/2.18.4', 'HTTP_CONNECTION': 'keep-alive', 'SERVER_NAME': '172.24.64.99', 'REMOTE_ADDR': '172.24.77.6', 'wsgi.run_once': False, 'wsgi.errors': <twisted.web.wsgi._ErrorStream object at 0x7f61265d9290>, 'wsgi.multiprocess': False, 'wsgi.url_scheme': 'http', 'SERVER_PORT': '8801', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate'}
2018-03-06 16:44:09,707.707 13569 DEBUG yabgp.api.v1 send_update_message 108 [-] Try to send update message to peer 172.24.76.173
2018-03-06 16:44:09,708.708 13569 ERROR yabgp.core.protocol send_update 284 [-] ubyte format requires 0 <= number <= 255

**Comment by meidli** [comment] 2018-03-20 07:23
@deepgajjar5 

The problem caused by the length limit of 23 path attribute(Tunnel Encapsulation). 
Our program permit segment list be add infinitely according to draft docs, but the 1 octet length field of path attribute entail that the length of Tunnel Encapsulation value can't exceed 255. So the number of segment list is finite, In your case, it can not exceed 6. 

We will enhance the exception handling about this.
thanks for your question, close.

**Comment by xiaopeng163** [comment] 2018-03-21 14:47
@deepgajjar5 we changed the attribute's flag to support extended length, now I think it will work, 
please get the latest master branch code and try again, thanks.

**Comment by xiaopeng163** [comment] 2018-03-26 03:06
@deepgajjar5 any comment?

**Comment by deepgajjar5** [comment] 2018-03-27 20:25
@xiaopeng163,

I have been able to send SLs with higher length (8 SLs) after pulling the latest branch. Thanks!

**Comment by xiaopeng163** [comment] 2018-03-28 00:11
good,  I will close this issue.

**Closed by xiaopeng163** 2018-03-28 00:11 UTC
